apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{  .Values.postgres.presistence.volumes.claimName  }}
  namespace: {{.Values.postgres.namespace}}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{  .Values.postgres.presistence.capacity  }}