apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot-deployment
  namespace: telegram
  labels:
    app: telegram-bot
spec:
  replicas: 1 # Number of bot instances you want running
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
      - name: telegram-bot-container
        image: nielh1/niel12-telegram-bot:latest # Your Docker Hub image!
        imagePullPolicy: Always
        env:
        - name: TELEGRAM_BOT_TOKEN # This is the variable name your Python code looks for
          valueFrom:
            secretKeyRef:
              name: bot-secrets # Matches the dynamic secret name from GitHub step 4
              key: BOT_TOKEN # Matches the key name from GitHub step 4