apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegram-bot-deployment
  namespace: telegram
  labels:
    app: telegram-bot
spec:
  replicas: 1 # Number of bot instances you want running
  selector:
    matchLabels:
      app: telegram-bot
  template:
    metadata:
      labels:
        app: telegram-bot
    spec:
      containers:
      - name: telegram-bot-container
        image: nielh1/niel12-telegram-bot:latest # Your Docker Hub image!
        imagePullPolicy: Always
        env:
        - name: TELEGRAM_BOT_TOKEN # This is the variable name your Python code looks for
          valueFrom:
            secretKeyRef:
              name: bot-secrets # Matches the dynamic secret name from GitHub step 4
              key: BOT_TOKEN # Matches the key name from GitHub step 4
        # --------------------------------------------------------
        # CONFIG MAP 
        # --------------------------------------------------------
        - name: LOG_LEVEL
          valueFrom:
            ConfigMapKeyRef:
              name: telegram-ConfigMap
              key: LOG_LEVEL
        - name: WELCOME_MESSAGE
          valueFrom:
            ConfigMapKeyRef:
              name: telegram-ConfigMap
              key: WELCOME_MESSAGE
        # --------------------------------------------------------
        # RESOURCE REQUESTS AND LIMITS
        # --------------------------------------------------------
          resources:
            requests: # how much it need to run minimum
              memory: "256Mi"
              cpu: "250m"
            limits: #restricts resources to a set amount to not consume too much
              memory: "512Mi"
              cpu: "500m"
        # --------------------------------------------------------
        # READINESS PROBE 
        # --------------------------------------------------------
          livenessProbe:
            exec:
              command:
              - python3
              - bot.py
              - --check
            initialDelaySeconds: 10
            periodSeconds: 15
        # -----------------------------------------------------------
        # VOLUMES/STORAGE
        # -----------------------------------------------------------
      volumes:
      - name: telegram-volume
        mountPath: /app/data
    volumes:
    - name: telegram-volume
      PersistentVolumeClaim:
        claimName: bot-pvc # matches pvc_link.yaml name