name: Build and Push Telegram Bot Image
on:
  push:
    branches:
      - Investigation

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and tag Docker Image
        run: |
          docker build -t nielh1/telegram-bot:latest -t nielh1/telegram-bot:${{ github.sha }} .

      - name: Push Docker Image
        run: |
          docker push nielh1/telegram-bot:latest
          docker push nielh1/telegram-bot:${{ github.sha }}