name: Deploy Telegram Bot to Kubernetes
on:
  push:
    branches:
      - main  # Triggers the pipeline every time you push code to the main branch
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    # 1. Log into your Docker Hub account using GitHub Secrets
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN}}

    # 2. Build and Push the updated image to Docker Hub
    - name: Build and Push Docker Image
      run: |
        docker build -t nielh1/niel12-telegram-bot:latest .
        docker push nielh1/niel12-telegram-bot:latest

    # conect github to tailscale network
    - name: Connect to Tailscale
      uses: tailscale/github-action@v2
      with:
        authkey: ${{ secrets.TAILSCALE_AUTHKEY }}

    # 3. Authenticate with your Kubernetes Cluster
    - name: Set up Kubernetes Context
      uses: azure/k8s-set-context@v3
      with:
        method: kubeconfig
        kubeconfig: ${{ secrets.KUBECONFIG }} # Your cluster connection details

    # 4. Dynamically generate the Kubernetes Secret using the GitHub Secret
    - name: Create Kubernetes Secret
      run: |
        kubectl create secret generic bot-secrets \
          --from-literal=BOT_TOKEN="${{ secrets.BOT_TOKEN }}" \
          -n my-custom-namespace \
          --dry-run=client -o yaml | kubectl apply -f -

    # 5. Deploy your bot app
    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f deployment.yaml -n my-custom-namespace